/**
 * Application Constants
 * Centralized configuration for the application
 */

import { InputOption, Tool, ToolCategory } from '../types';

export const TOOL_CATEGORIES: ToolCategory[] = [
  {
    id: 'manipulation',
    name: 'PDF Manipulation',
    icon: 'edit',
    description: 'Organize, split, merge, and manage PDF pages',
  },
  {
    id: 'convert-to-pdf',
    name: 'Convert to PDF',
    icon: 'upload_file',
    description: 'Convert various file formats to PDF',
  },
  {
    id: 'convert-from-pdf',
    name: 'Convert from PDF',
    icon: 'download',
    description: 'Export PDF to other formats',
  },
  {
    id: 'editing',
    name: 'Editing & Enhancement',
    icon: 'auto_fix_high',
    description: 'Edit, annotate, and enhance PDF documents',
  },
  {
    id: 'security',
    name: 'Security & Privacy',
    icon: 'shield',
    description: 'Protect and manage PDF security',
  },
  {
    id: 'extraction',
    name: 'Analysis & Extraction',
    icon: 'content_copy',
    description: 'Extract content from PDF documents',
  },
  {
    id: 'quality',
    name: 'Quality & Repair',
    icon: 'build_circle',
    description: 'Optimize and fix PDF issues',
  },
  {
    id: 'formatting',
    name: 'Formatting & Layout',
    icon: 'format_align_left',
    description: 'Format and structure PDF documents',
  },
  {
    id: 'advanced',
    name: 'Advanced Tools',
    icon: 'settings',
    description: 'Specialized and batch operations',
  },
] as const;

export const APP_CONFIG = {
  name: 'DataBits Convert',
  version: '1.0.0',
  description: 'Online converter for your documents',
  maxFileSize: 50 * 1024 * 1024, // 50MB
  supportedImageFormats: [
    'image/jpeg',
    'image/png',
    'image/gif',
    'image/webp',
    'image/bmp',
    'image/svg+xml',
    'image/heic',
    'image/tiff',
  ],
  supportedPdfFormat: 'application/pdf',
} as const;

export const INPUT_OPTIONS: InputOption[] = [
  { id: 'gdrive', label: 'Google Drive', icon: 'add_to_drive' },
  { id: 'onedrive', label: 'OneDrive', icon: 'cloud_upload' },
  { id: 'dropbox', label: 'Dropbox', icon: 'inventory_2' },
  { id: 'url', label: 'URL', icon: 'link' },
] as const;

export const POPULAR_TOOLS: Tool[] = [
  // PDF Manipulation
  {
    id: 'merge',
    name: 'Merge PDF',
    icon: 'call_merge',
    description: 'Combine multiple PDFs into one file.',
    category: 'manipulation',
  },
  {
    id: 'split',
    name: 'Split PDF',
    icon: 'call_split',
    description: 'Extract a range of pages into a new PDF.',
    category: 'manipulation',
  },
  {
    id: 'compress',
    name: 'Compress PDF',
    icon: 'compress',
    description: 'Reduce the file size of your PDF.',
    category: 'manipulation',
  },
  {
    id: 'organize',
    name: 'Organize PDF',
    icon: 'library_books',
    description: 'Sort, reorder, and delete pages.',
    category: 'manipulation',
  },
  {
    id: 'delete',
    name: 'Delete Pages',
    icon: 'delete',
    description: 'Remove unwanted pages.',
    category: 'manipulation',
  },
  {
    id: 'extract',
    name: 'Extract Pages',
    icon: 'file_upload',
    description: 'Save specific pages as new files.',
    category: 'manipulation',
  },
  {
    id: 'crop',
    name: 'Crop PDF',
    icon: 'crop',
    description: 'Trim the margins of your PDF pages.',
    category: 'manipulation',
  },
  {
    id: 'rotate',
    name: 'Rotate PDF',
    icon: 'rotate_right',
    description: 'Rotate PDF pages to any angle.',
    category: 'manipulation',
  },
  {
    id: 'reverse',
    name: 'Reverse Pages',
    icon: 'call_received',
    description: 'Reverse the order of PDF pages.',
    category: 'manipulation',
  },
  {
    id: 'duplicate',
    name: 'Duplicate Pages',
    icon: 'copy_all',
    description: 'Duplicate pages within your PDF.',
    category: 'manipulation',
  },
  {
    id: 'divide',
    name: 'Divide Pages',
    icon: 'call_split',
    description: 'Split pages into smaller sections.',
    category: 'manipulation',
  },
  {
    id: 'page-numbers',
    name: 'Add Page Numbers',
    icon: 'numbers',
    description: 'Add page numbers to your PDF.',
    category: 'manipulation',
  },
  {
    id: 'page-dimensions',
    name: 'Fix Page Size',
    icon: 'aspect_ratio',
    description: 'Adjust or standardize page dimensions.',
    category: 'manipulation',
  },
  {
    id: 'n-up',
    name: 'N-Up PDF',
    icon: 'dashboard',
    description: 'Place multiple pages on a single sheet.',
    category: 'manipulation',
  },

  // PDF Conversions - To PDF
  {
    id: 'image-to-pdf',
    name: 'Image to PDF',
    icon: 'image',
    description: 'Convert images to PDF.',
    category: 'convert-to-pdf',
  },
  {
    id: 'word-to-pdf',
    name: 'Word to PDF',
    icon: 'document_scanner',
    description: 'Convert Word document to PDF.',
    category: 'convert-to-pdf',
  },
  {
    id: 'jpg-to-pdf',
    name: 'JPG to PDF',
    icon: 'image',
    description: 'Convert JPG images to PDF.',
    category: 'convert-to-pdf',
  },
  {
    id: 'png-to-pdf',
    name: 'PNG to PDF',
    icon: 'image',
    description: 'Convert PNG images to PDF.',
    category: 'convert-to-pdf',
  },
  {
    id: 'bmp-to-pdf',
    name: 'BMP to PDF',
    icon: 'image',
    description: 'Convert BMP images to PDF.',
    category: 'convert-to-pdf',
  },
  {
    id: 'webp-to-pdf',
    name: 'WebP to PDF',
    icon: 'image',
    description: 'Convert WebP images to PDF.',
    category: 'convert-to-pdf',
  },
  {
    id: 'heic-to-pdf',
    name: 'HEIC to PDF',
    icon: 'image',
    description: 'Convert HEIC images to PDF.',
    category: 'convert-to-pdf',
  },
  {
    id: 'svg-to-pdf',
    name: 'SVG to PDF',
    icon: 'image',
    description: 'Convert SVG graphics to PDF.',
    category: 'convert-to-pdf',
  },
  {
    id: 'tiff-to-pdf',
    name: 'TIFF to PDF',
    icon: 'image',
    description: 'Convert TIFF images to PDF.',
    category: 'convert-to-pdf',
  },
  {
    id: 'email-to-pdf',
    name: 'Email to PDF',
    icon: 'mail',
    description: 'Convert email messages to PDF.',
    category: 'convert-to-pdf',
  },
  {
    id: 'txt-to-pdf',
    name: 'Text to PDF',
    icon: 'description',
    description: 'Convert text files to PDF.',
    category: 'convert-to-pdf',
  },
  {
    id: 'csv-to-pdf',
    name: 'CSV to PDF',
    icon: 'table_chart',
    description: 'Convert CSV spreadsheets to PDF.',
    category: 'convert-to-pdf',
  },
  {
    id: 'json-to-pdf',
    name: 'JSON to PDF',
    icon: 'data_object',
    description: 'Convert JSON data to PDF.',
    category: 'convert-to-pdf',
  },
  {
    id: 'markdown-to-pdf',
    name: 'Markdown to PDF',
    icon: 'description',
    description: 'Convert Markdown files to PDF.',
    category: 'convert-to-pdf',
  },
  {
    id: 'excel-to-pdf',
    name: 'Excel to PDF',
    icon: 'grid_on',
    description: 'Convert Excel spreadsheets to PDF.',
    category: 'convert-to-pdf',
  },
  {
    id: 'powerpoint-to-pdf',
    name: 'PowerPoint to PDF',
    icon: 'slideshow',
    description: 'Convert PowerPoint presentations to PDF.',
    category: 'convert-to-pdf',
  },
  {
    id: 'epub-to-pdf',
    name: 'EPUB to PDF',
    icon: 'menu_book',
    description: 'Convert EPUB ebooks to PDF.',
    category: 'convert-to-pdf',
  },
  {
    id: 'mobi-to-pdf',
    name: 'MOBI to PDF',
    icon: 'menu_book',
    description: 'Convert MOBI ebooks to PDF.',
    category: 'convert-to-pdf',
  },
  {
    id: 'cbz-to-pdf',
    name: 'CBZ to PDF',
    icon: 'library_books',
    description: 'Convert comic archives to PDF.',
    category: 'convert-to-pdf',
  },
  {
    id: 'fb2-to-pdf',
    name: 'FB2 to PDF',
    icon: 'menu_book',
    description: 'Convert FB2 ebooks to PDF.',
    category: 'convert-to-pdf',
  },
  {
    id: 'rtf-to-pdf',
    name: 'RTF to PDF',
    icon: 'description',
    description: 'Convert RTF documents to PDF.',
    category: 'convert-to-pdf',
  },
  {
    id: 'odg-to-pdf',
    name: 'ODG to PDF',
    icon: 'image',
    description: 'Convert ODG drawings to PDF.',
    category: 'convert-to-pdf',
  },
  {
    id: 'odp-to-pdf',
    name: 'ODP to PDF',
    icon: 'slideshow',
    description: 'Convert ODP presentations to PDF.',
    category: 'convert-to-pdf',
  },
  {
    id: 'ods-to-pdf',
    name: 'ODS to PDF',
    icon: 'grid_on',
    description: 'Convert ODS spreadsheets to PDF.',
    category: 'convert-to-pdf',
  },
  {
    id: 'odt-to-pdf',
    name: 'ODT to PDF',
    icon: 'description',
    description: 'Convert ODT documents to PDF.',
    category: 'convert-to-pdf',
  },
  {
    id: 'psd-to-pdf',
    name: 'PSD to PDF',
    icon: 'palette',
    description: 'Convert Photoshop files to PDF.',
    category: 'convert-to-pdf',
  },
  {
    id: 'vsd-to-pdf',
    name: 'VSD to PDF',
    icon: 'dashboard',
    description: 'Convert Visio diagrams to PDF.',
    category: 'convert-to-pdf',
  },
  {
    id: 'wpd-to-pdf',
    name: 'WPD to PDF',
    icon: 'description',
    description: 'Convert WordPerfect documents to PDF.',
    category: 'convert-to-pdf',
  },
  {
    id: 'wps-to-pdf',
    name: 'WPS to PDF',
    icon: 'description',
    description: 'Convert WPS documents to PDF.',
    category: 'convert-to-pdf',
  },
  {
    id: 'pub-to-pdf',
    name: 'PUB to PDF',
    icon: 'description',
    description: 'Convert Publisher documents to PDF.',
    category: 'convert-to-pdf',
  },
  {
    id: 'xml-to-pdf',
    name: 'XML to PDF',
    icon: 'code',
    description: 'Convert XML files to PDF.',
    category: 'convert-to-pdf',
  },
  {
    id: 'xps-to-pdf',
    name: 'XPS to PDF',
    icon: 'description',
    description: 'Convert XPS documents to PDF.',
    category: 'convert-to-pdf',
  },

  // PDF Conversions - From PDF
  {
    id: 'pdf-to-word',
    name: 'PDF to Word',
    icon: 'file-text',
    description: 'Convert PDF to DOCX using PyMuPDF.',
    category: 'convert-from-pdf',
  },
  {
    id: 'pdf-to-jpg',
    name: 'PDF to JPG',
    icon: 'image',
    description: 'Convert PDF pages to JPG images.',
    category: 'convert-from-pdf',
  },
  {
    id: 'pdf-to-png',
    name: 'PDF to PNG',
    icon: 'image',
    description: 'Convert PDF pages to PNG images.',
    category: 'convert-from-pdf',
  },
  {
    id: 'pdf-to-bmp',
    name: 'PDF to BMP',
    icon: 'image',
    description: 'Convert PDF pages to BMP images.',
    category: 'convert-from-pdf',
  },
  {
    id: 'pdf-to-webp',
    name: 'PDF to WebP',
    icon: 'image',
    description: 'Convert PDF pages to WebP images.',
    category: 'convert-from-pdf',
  },
  {
    id: 'pdf-to-svg',
    name: 'PDF to SVG',
    icon: 'image',
    description: 'Convert PDF pages to SVG graphics.',
    category: 'convert-from-pdf',
  },
  {
    id: 'pdf-to-tiff',
    name: 'PDF to TIFF',
    icon: 'image',
    description: 'Convert PDF pages to TIFF images.',
    category: 'convert-from-pdf',
  },
  {
    id: 'pdf-to-text',
    name: 'PDF to Text',
    icon: 'description',
    description: 'Extract text from PDF.',
    category: 'convert-from-pdf',
  },
  {
    id: 'pdf-to-excel',
    name: 'PDF to Excel',
    icon: 'grid_on',
    description: 'Convert PDF tables to Excel.',
    category: 'convert-from-pdf',
  },
  {
    id: 'pdf-to-csv',
    name: 'PDF to CSV',
    icon: 'table_chart',
    description: 'Convert PDF tables to CSV.',
    category: 'convert-from-pdf',
  },
  {
    id: 'pdf-to-json',
    name: 'PDF to JSON',
    icon: 'data_object',
    description: 'Extract PDF data as JSON.',
    category: 'convert-from-pdf',
  },
  {
    id: 'pdf-to-markdown',
    name: 'PDF to Markdown',
    icon: 'description',
    description: 'Convert PDF to Markdown format.',
    category: 'convert-from-pdf',
  },
  {
    id: 'pdf-to-zip',
    name: 'PDF to ZIP',
    icon: 'folder_zip',
    description: 'Export PDF pages as a ZIP archive.',
    category: 'convert-from-pdf',
  },

  // PDF Editing & Enhancement
  {
    id: 'edit',
    name: 'PDF Editor',
    icon: 'edit',
    description: 'Annotate, highlight, and add comments.',
    category: 'editing',
  },
  {
    id: 'sign',
    name: 'Sign PDF',
    icon: 'draw',
    description: 'Add your signature to a PDF.',
    category: 'editing',
  },
  {
    id: 'digital-sign',
    name: 'Digital Signature',
    icon: 'verified',
    description: 'Add digital signatures to PDF.',
    category: 'editing',
  },
  {
    id: 'validate-signature',
    name: 'Validate Signatures',
    icon: 'task_alt',
    description: 'Verify PDF digital signatures.',
    category: 'editing',
  },
  {
    id: 'add-stamps',
    name: 'Add Stamps',
    icon: 'sell',
    description: 'Add stamps and watermarks to PDF.',
    category: 'editing',
  },
  {
    id: 'add-watermark',
    name: 'Add Watermark',
    icon: 'water_drop',
    description: 'Add watermarks to PDF pages.',
    category: 'editing',
  },
  {
    id: 'add-attachments',
    name: 'Add Attachments',
    icon: 'attach_file',
    description: 'Embed files in PDF.',
    category: 'editing',
  },
  {
    id: 'extract-attachments',
    name: 'Extract Attachments',
    icon: 'download',
    description: 'Extract embedded files from PDF.',
    category: 'editing',
  },
  {
    id: 'edit-attachments',
    name: 'Edit Attachments',
    icon: 'edit',
    description: 'Manage PDF attachments.',
    category: 'editing',
  },
  {
    id: 'add-blank-page',
    name: 'Add Blank Page',
    icon: 'add_to_photos',
    description: 'Insert blank pages into PDF.',
    category: 'editing',
  },
  {
    id: 'header-footer',
    name: 'Add Headers/Footers',
    icon: 'article',
    description: 'Add headers and footers to PDF.',
    category: 'editing',
  },
  {
    id: 'background-color',
    name: 'Background Color',
    icon: 'brush',
    description: 'Change PDF page background.',
    category: 'editing',
  },
  {
    id: 'text-color',
    name: 'Text Color',
    icon: 'format_color_text',
    description: 'Modify text colors in PDF.',
    category: 'editing',
  },
  {
    id: 'invert-colors',
    name: 'Invert Colors',
    icon: 'contrast',
    description: 'Invert colors in PDF.',
    category: 'editing',
  },
  {
    id: 'adjust-colors',
    name: 'Adjust Colors',
    icon: 'color_lens',
    description: 'Fine-tune PDF colors.',
    category: 'editing',
  },
  {
    id: 'grayscale',
    name: 'Convert to Grayscale',
    icon: 'monochrome_photos',
    description: 'Convert PDF to grayscale.',
    category: 'editing',
  },
  {
    id: 'posterize',
    name: 'Posterize',
    icon: 'palette',
    description: 'Create posterized PDF effect.',
    category: 'editing',
  },
  {
    id: 'rotate-custom',
    name: 'Custom Rotation',
    icon: 'rotate_90_degrees_ccw',
    description: 'Rotate pages by custom angles.',
    category: 'editing',
  },
  {
    id: 'rasterize',
    name: 'Rasterize',
    icon: 'image',
    description: 'Convert vector elements to raster.',
    category: 'editing',
  },
  {
    id: 'flatten',
    name: 'Flatten PDF',
    icon: 'check',
    description: 'Merge all layers into one.',
    category: 'editing',
  },
  {
    id: 'linearize',
    name: 'Linearize PDF',
    icon: 'trending_flat',
    description: 'Optimize PDF for web viewing.',
    category: 'editing',
  },
  {
    id: 'sanitize',
    name: 'Sanitize PDF',
    icon: 'cleaning_services',
    description: 'Remove sensitive data from PDF.',
    category: 'editing',
  },

  // PDF Security & Metadata
  {
    id: 'encrypt',
    name: 'Encrypt PDF',
    icon: 'lock',
    description: 'Add password protection to PDF.',
    category: 'security',
  },
  {
    id: 'decrypt',
    name: 'Decrypt PDF',
    icon: 'lock_open',
    description: 'Remove PDF password protection.',
    category: 'security',
  },
  {
    id: 'change-permissions',
    name: 'Change Permissions',
    icon: 'security',
    description: 'Modify PDF access permissions.',
    category: 'security',
  },
  {
    id: 'remove-metadata',
    name: 'Remove Metadata',
    icon: 'delete',
    description: 'Strip metadata from PDF.',
    category: 'security',
  },
  {
    id: 'edit-metadata',
    name: 'Edit Metadata',
    icon: 'edit',
    description: 'Modify PDF metadata.',
    category: 'security',
  },
  {
    id: 'view-metadata',
    name: 'View Metadata',
    icon: 'info',
    description: 'View PDF document properties.',
    category: 'security',
  },
  {
    id: 'remove-restrictions',
    name: 'Remove Restrictions',
    icon: 'lock_open',
    description: 'Remove PDF restrictions.',
    category: 'security',
  },
  {
    id: 'remove-annotations',
    name: 'Remove Annotations',
    icon: 'close',
    description: 'Remove comments and markups from PDF.',
    category: 'security',
  },

  // PDF Analysis & Extraction
  {
    id: 'extract-images',
    name: 'Extract Images',
    icon: 'image',
    description: 'Extract images from PDF.',
    category: 'extraction',
  },
  {
    id: 'extract-tables',
    name: 'Extract Tables',
    icon: 'table_chart',
    description: 'Extract tables from PDF.',
    category: 'extraction',
  },
  {
    id: 'ocr',
    name: 'OCR (Text Recognition)',
    icon: 'receipt',
    description: 'Recognize text in scanned PDFs.',
    category: 'extraction',
  },
  {
    id: 'prepare-for-ai',
    name: 'Prepare for AI',
    icon: 'smart_toy',
    description: 'Optimize PDF for AI processing.',
    category: 'extraction',
  },

  // PDF Quality & Repair
  {
    id: 'deskew',
    name: 'Deskew PDF',
    icon: 'align_horizontal_left',
    description: 'Straighten skewed PDF pages.',
    category: 'quality',
  },
  {
    id: 'remove-blank-pages',
    name: 'Remove Blank Pages',
    icon: 'filter_alt',
    description: 'Remove empty pages.',
    category: 'quality',
  },
  {
    id: 'repair',
    name: 'Repair PDF',
    icon: 'build',
    description: 'Fix corrupted PDF files.',
    category: 'quality',
  },
  {
    id: 'fix-page-size',
    name: 'Fix Page Size',
    icon: 'aspect_ratio',
    description: 'Standardize page dimensions.',
    category: 'quality',
  },
  {
    id: 'scanner-effect',
    name: 'Scanner Effect',
    icon: 'scanner',
    description: 'Apply scanner-like appearance.',
    category: 'quality',
  },
  {
    id: 'scan-to-pdf',
    name: 'Scan to PDF',
    icon: 'scanner',
    description: 'Convert scanned images to PDF.',
    category: 'quality',
  },

  // PDF Formatting & Layout
  {
    id: 'booklet',
    name: 'Create Booklet',
    icon: 'auto_stories',
    description: 'Arrange pages for booklet printing.',
    category: 'formatting',
  },
  {
    id: 'bates-numbering',
    name: 'Bates Numbering',
    icon: 'tag',
    description: 'Add legal Bates numbers.',
    category: 'formatting',
  },
  {
    id: 'table-of-contents',
    name: 'Add Table of Contents',
    icon: 'list_alt',
    description: 'Generate PDF table of contents.',
    category: 'formatting',
  },
  {
    id: 'bookmark',
    name: 'Add Bookmarks',
    icon: 'bookmark',
    description: 'Create PDF bookmarks/outlines.',
    category: 'formatting',
  },
  {
    id: 'layers',
    name: 'PDF Layers',
    icon: 'layers',
    description: 'Manage PDF layers.',
    category: 'formatting',
  },
  {
    id: 'font-to-outline',
    name: 'Font to Outline',
    icon: 'text_fields',
    description: 'Convert fonts to outlines.',
    category: 'formatting',
  },
  {
    id: 'pdf-to-pdfa',
    name: 'Convert to PDF/A',
    icon: 'archive',
    description: 'Convert to PDF/A archival format.',
    category: 'formatting',
  },
  {
    id: 'compare-pdfs',
    name: 'Compare PDFs',
    icon: 'compare',
    description: 'Compare two PDF documents.',
    category: 'formatting',
  },

  // Merge Variations
  {
    id: 'alternate-merge',
    name: 'Alternate Merge',
    icon: 'call_merge',
    description: 'Merge PDFs by alternating pages.',
    category: 'formatting',
  },
  {
    id: 'combine-single-page',
    name: 'Combine to Single Page',
    icon: 'call_merge',
    description: 'Merge PDFs into single pages.',
    category: 'formatting',
  },

  // Advanced Tools
  {
    id: 'pdf-workflow',
    name: 'PDF Workflow',
    icon: 'auto_awesome',
    description: 'Automated multi-step PDF processing.',
    category: 'advanced',
  },
  {
    id: 'form-creator',
    name: 'Form Creator',
    icon: 'apps',
    description: 'Create fillable PDF forms.',
    category: 'advanced',
  },
  {
    id: 'form-filler',
    name: 'Form Filler',
    icon: 'edit',
    description: 'Automatically fill PDF forms.',
    category: 'advanced',
  },
] as const;

export const ERROR_MESSAGES = {
  FILE_TOO_LARGE: `File size exceeds ${APP_CONFIG.maxFileSize / 1024 / 1024}MB limit`,
  UNSUPPORTED_FORMAT: 'Unsupported file format',
  NETWORK_ERROR: 'Network error occurred. Please check your connection.',
  OAUTH_NOT_CONFIGURED: 'OAuth is not configured for this provider',
  INVALID_URL: 'Invalid URL provided',
  FETCH_FAILED: 'Failed to fetch file from URL',
  CORS_ERROR: 'CORS restrictions prevent loading from this domain',
} as const;

export const SUCCESS_MESSAGES = {
  FILE_UPLOADED: 'File uploaded successfully',
  CONVERSION_COMPLETE: 'Conversion completed',
  DOWNLOAD_READY: 'Your file is ready to download',
} as const;
